platform :ios, "7.0"

source 'https://github.com/CocoaPods/Specs.git'

pod 'MCAdditions', :git => 'https://github.com/matthewcheok/MCAdditions.git'
pod 'AFNetworking'

pod 'MCAppRouter', '~> 0.1'
pod 'MCModalView', '~> 0.2'
pod 'MCDynamicObject', '~> 0.2'

pod 'ChameleonFramework', '~>1.1'
pod 'MCModalView', '~>0.2'

pod 'DateTools', '~> 1.4'

pod 'Facebook-iOS-SDK', '~> 3.23'
pod 'Parse', '~> 1.6'
pod 'JGProgressHUD'

pod 'POP+MCAnimate', '~> 2.0'

pod 'JSQMessagesViewController', '5.2.2'
pod 'SDWebImage', '~> 3.7'

pod 'Reveal-iOS-SDK', :configurations => ['Debug']
pod 'Jibber-Framework', '~> 1.1', :configurations => ['Debug']

pod 'Firebase', '>= 2.2.0'
pod 'GPUImage'
pod 'RNFrostedSidebar', '~> 0.2.0' 